# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  
jobs:
  build:

    runs-on: ubuntu-latest
   
    strategy:
      matrix:
        java: [ '8' ]
       
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run the Helloworld App
      run: |
         ls
         java -jar target/helloworld.jar

    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: chandra25ms/springboot-helloworld:latest

    - name: Run Helloworld Application
      run: |
            docker run --name hello -i chandra25ms/springboot-helloworld:latest
            docker logs hello > hello.txt
            cat hello.txt
